name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write # 🚨 This is required for pushing to the repo

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: codexboy0417
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#39ff14&color_dots=#1a1a1a,#2a2a2a,#3a3a3a,#4a4a4a,#5a5a5a

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generated GitHub Snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
